site_name: ScurryPy
site_url: https://furmissile.github.io/scurrypy/

theme: # https://squidfunk.github.io/mkdocs-material/setup/changing-the-colors/#changing-the-colors
  name: material
  logo: assets/wizard.svg
  favicon: assets/wizard.svg
  font:
    text: Source Serif Pro
  features:
    - content.code.copy
    - navigation.sections
    - header.repo
    - content.tabs.link
    - navigation.top
    - navigation.tabs
    - navigation.tabs.sticky
  icon:
    repo: fontawesome/brands/github
  palette:
    # Palette toggle for light mode
    - scheme: default
      primary: green
      accent: deep purple
      toggle:
        icon: material/weather-night
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      primary: deep purple # header, the sidebar, text links, etc.
      accent: green # interactive components
      toggle: # https://squidfunk.github.io/mkdocs-material/setup/changing-the-colors/#color-palette-toggle
        icon: material/weather-sunny
        name: Switch to light mode

repo_url: https://github.com/Furmissile/scurrypy

markdown_extensions:
  - md_in_html
  - admonition
  - attr_list
  - tables
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.highlight:
      linenums: true
      anchor_linenums: true
  - toc:
      permalink: true
  - pymdownx.superfences

extra_css:
  - css/custom_color.css
  - css/header.css
  - css/text_alignment.css

copyright: Copyright &copy; 2025 Furmissile

plugins:
  - search
  - autorefs
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_section_style: list
            inherited_members: true
            merge_init_into_class: true
            show_symbol_type_toc: true
            show_inheritance_diagram: true
            show_root_heading: true
            show_root_full_path: false
            show_signature_annotations: true
            show_signature_type_parameters: true
            show_source: false
            show_symbol_type_heading: true
            docstring_style: google
            members_order: source
            filters:
              - "!from_dict"
              - "!^_"

watch:
  - scurrypy
  - docs

nav:
  - Home: index.md
  - FAQ: faq.md
  - Footnotes: doc_notes.md
  - Getting Started:
    - Start Here!: getting_started/start_here.md
    - Examples: getting_started/examples.md
    - Addons: getting_started/addons.md
    - Logging: getting_started/logging.md
    - Migrations: getting_started/migrating.md
  - API Reference:
    - Overview: api/index.md
    - Addon: api/addon.md
    - Channel: api/channel.md
    - Client: api/client.md
    - Commands: api/commands.md
    - Component Types: api/component_types.md
    - Components: api/components.md
    - Embed (Legacy): api/embed.md
    - Intents: api/intents.md
    - Message: api/message.md
    - Models: api/models.md
    - Permissions: api/permissions.md
    - Role: api/role.md
    - UI Components: api/ui_components.md
  - Events:
    - Overview: events/index.md
    - Channel: events/channel.md
    - Event Types: events/event_types.md
    - Guild: events/guild.md
    - Interaction: events/interaction.md
    - Message: events/message.md
    - Reaction: events/reaction.md
    - Ready: events/ready.md
    - Role: events/role.md
  - Resources:
    - Overview: resources/index.md
    - Application: resources/application.md
    - Bot Emoji: resources/bot_emojis.md
    - Channel: resources/channel.md
    - Command: resources/command.md
    - Guild Emoji: resources/guild_emoji.md
    - Guild: resources/guild.md
    - Interaction: resources/interaction.md
    - Message: resources/message.md
    - User: resources/user.md
  - Internals:
    - Overview: internals/index.md
    - Base Models: internals/model.md
    - Discord Error: internals/error.md
    - Gateway: internals/gateway.md
    - HTTP: internals/http.md
    - Technical Writeup: internals/technical_writeup.md
